// Generated by CoffeeScript 1.12.7

/*
Codegenable parse tree nodes for LOLCODE. The nodes are organized into a
hierarchy rooted at LOLCoffee.AST.Node:
  Node
    Program
    Statement
      FunctionDefinition
      Declaration
      Return
      Input
      Output
      Assignment
      IndexedAssignment
      Break
      Loop
      Conditional
      Switch
      StatementList
      Expression
        IdentifierExpression
        IndexingExpression
        CastExpression
        CallExpression
        UnaryExpression
        BinaryExpression
        InfinitaryExpression
        Literal
          NullLiteral
          BoolLiteral
          IntLiteral
          FloatLiteral
          StringLiteral

Each node has a codegen method that takes a CodeGenContext and emits the
instructions and labels that implement the node. The CodeGenContext keeps track
of the labels and instructions created by the nodes. It can be used to codegen
multiple programs. Each time it is used, the new instructions and labels are
appended to the existing ones. This allows multiple programs to run on the same
VM and share globals, as in the context of a REPL.

Example usage:
  parsed_program_1 = ...
  parsed_program_2 = ...
  codegen_context = new LOLCoffee.CodeGenContext
  try
    parsed_program_1.codegen codegen_context
     * Can now sync the VM to codegen_context and run the first program.
    parsed_program_2.codegen codegen_context
     * Can now sync the VM to codegen_context and run the second program.
  catch error
    console.assert error instanceof LOLCoffee.CodeGenError
    console.log error

Provides:
  LOLCoffee.CodeGenError
  LOLCoffee.CodeGenContext
  LOLCoffee.AST

Requires:
  LOLCoffee.Instructions
 */

(function() {
  var Assignment, BinaryExpression, BoolLiteral, Break, BukkitLiteral, CallExpression, CastExpression, CodeGenContext, CodeGenError, Conditional, Declaration, Expression, FloatLiteral, FunctionDefinition, IdentifierExpression, IndexedAssignment, IndexingExpression, InfinitaryExpression, Input, Instructions, IntLiteral, Literal, Loop, Node, NullLiteral, Output, Program, PropertyAccessExpression, PropertyAssignment, Return, Statement, StatementList, StringLiteral, Switch, UnaryExpression,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Instructions = this.LOLCoffee.Instructions;

  CodeGenError = (function(superClass) {
    extend(CodeGenError, superClass);

    function CodeGenError(message) {
      CodeGenError.__super__.constructor.call(this, message);
      this.message = message;
    }

    CodeGenError.prototype.name = 'CodeGenError';

    return CodeGenError;

  })(Error);

  CodeGenContext = (function() {
    function CodeGenContext() {
      this.instructions = [];
      this.labels = [];
      this._break_stack = [];
    }

    CodeGenContext.prototype.emit = function(instruction) {
      return this.instructions.push(instruction);
    };

    CodeGenContext.prototype.newLabel = function() {
      this.labels.push(null);
      return this.labels.length - 1;
    };

    CodeGenContext.prototype.emitLabel = function(label) {
      if (label >= this.labels.length) {
        throw new CodeGenError("Unknown label (" + label + "). Top: " + this.labels.length);
      }
      return this.labels[label] = this.instructions.length;
    };

    CodeGenContext.prototype.getBreakLabel = function() {
      return this._break_stack[this._break_stack.length - 1];
    };

    CodeGenContext.prototype.popBreakLabel = function() {
      return this._break_stack.pop();
    };

    CodeGenContext.prototype.pushBreakLabel = function(label) {
      return this._break_stack.push(label);
    };

    return CodeGenContext;

  })();

  Node = (function() {
    function Node() {}

    return Node;

  })();

  Program = (function(superClass) {
    extend(Program, superClass);

    function Program(body1) {
      this.body = body1;
    }

    Program.prototype.codegen = function(context) {
      this.body.codegen(context);
      return context.emit(new Instructions.Halt);
    };

    return Program;

  })(Node);

  FunctionDefinition = (function(superClass) {
    extend(FunctionDefinition, superClass);

    function FunctionDefinition(name, args, body1) {
      this.name = name;
      this.args = args;
      this.body = body1;
    }

    FunctionDefinition.prototype.codegen = function(context) {
      var arg, end_label, i, len, ref, start_label;
      start_label = context.newLabel();
      end_label = context.newLabel();
      context.emit(new Instructions.DeclareFunction(this.name, start_label));
      context.emit(new Instructions.Jump(end_label));
      context.emitLabel(start_label);
      this.args.reverse();
      ref = this.args;
      for (i = 0, len = ref.length; i < len; i++) {
        arg = ref[i];
        context.emit(new Instructions.DeclareVariable(arg));
        context.emit(new Instructions.Assign(arg));
      }
      this.body.codegen(context);
      return context.emitLabel(end_label);
    };

    return FunctionDefinition;

  })(Node);

  Statement = (function(superClass) {
    extend(Statement, superClass);

    function Statement() {
      return Statement.__super__.constructor.apply(this, arguments);
    }

    return Statement;

  })(Node);

  Return = (function(superClass) {
    extend(Return, superClass);

    function Return(value) {
      this.value = value;
    }

    Return.prototype.codegen = function(context) {
      this.value.codegen(context);
      return context.emit(new Instructions.Return);
    };

    return Return;

  })(Statement);

  Input = (function(superClass) {
    extend(Input, superClass);

    function Input(identifier) {
      this.identifier = identifier;
    }

    Input.prototype.codegen = function(context) {
      context.emit(new Instructions.Input);
      context.emit(new Instructions.PushSyscallResult);
      return context.emit(new Instructions.Assign(this.identifier));
    };

    return Input;

  })(Statement);

  Output = (function(superClass) {
    extend(Output, superClass);

    function Output(expression) {
      this.expression = expression;
    }

    Output.prototype.codegen = function(context) {
      this.expression.codegen(context);
      return context.emit(new Instructions.Output);
    };

    return Output;

  })(Statement);

  Declaration = (function(superClass) {
    extend(Declaration, superClass);

    function Declaration(identifier) {
      this.identifier = identifier;
    }

    Declaration.prototype.codegen = function(context) {
      return context.emit(new Instructions.DeclareVariable(this.identifier));
    };

    return Declaration;

  })(Statement);

  Assignment = (function(superClass) {
    extend(Assignment, superClass);

    function Assignment(identifier, value) {
      this.identifier = identifier;
      this.value = value;
    }

    Assignment.prototype.codegen = function(context) {
      this.value.codegen(context);
      return context.emit(new Instructions.Assign(this.identifier));
    };

    return Assignment;

  })(Statement);

  IndexedAssignment = (function(superClass) {
    extend(IndexedAssignment, superClass);

    function IndexedAssignment(identifier, index, value) {
      this.identifier = identifier;
      this.index = index;
      this.value = value;
    }

    IndexedAssignment.prototype.codegen = function(context) {
      this.value.codegen(context);
      this.index.codegen(context);
      return context.emit(new Instructions.AssignAtIndex(this.identifier));
    };

    return IndexedAssignment;

  })(Statement);

  PropertyAssignment = (function(superClass) {
    extend(PropertyAssignment, superClass);

    function PropertyAssignment(identifier, property, value) {
      this.identifier = identifier;
      this.property = property;
      this.value = value;
    }

    PropertyAssignment.prototype.codegen = function(context) {
      this.value.codegen(context);
      return context.emit(new Instructions.SetProperty(this.identifier, this.property));
    };

    return PropertyAssignment;

  })(Statement);

  Break = (function(superClass) {
    extend(Break, superClass);

    function Break() {}

    Break.prototype.codegen = function(context) {
      return context.emit(new Instructions.Jump(context.getBreakLabel()));
    };

    return Break;

  })(Statement);

  StatementList = (function(superClass) {
    extend(StatementList, superClass);

    function StatementList(statements) {
      this.statements = statements;
    }

    StatementList.prototype.codegen = function(context) {
      var i, len, ref, results, statement;
      ref = this.statements;
      results = [];
      for (i = 0, len = ref.length; i < len; i++) {
        statement = ref[i];
        results.push(statement.codegen(context));
      }
      return results;
    };

    return StatementList;

  })(Statement);

  Conditional = (function(superClass) {
    extend(Conditional, superClass);

    function Conditional(then_body, else_body) {
      this.then_body = then_body;
      this.else_body = else_body;
    }

    Conditional.prototype.codegen = function(context) {
      var else_label, end_label;
      else_label = context.newLabel();
      end_label = context.newLabel();
      context.emit(new Instructions.PushVariable('IT'));
      context.emit(new Instructions.Cast('bool'));
      context.emit(new Instructions.JumpIfZero(else_label));
      this.then_body.codegen(context);
      context.emit(new Instructions.Jump(end_label));
      context.emitLabel(else_label);
      if (this.else_body) {
        this.else_body.codegen(context);
      }
      return context.emitLabel(end_label);
    };

    return Conditional;

  })(Statement);

  Switch = (function(superClass) {
    extend(Switch, superClass);

    function Switch(cases, default_case) {
      this.cases = cases;
      this.default_case = default_case;
    }

    Switch.prototype.codegen = function(context) {
      var _, body, case_tuple, condition, default_label, end_label, i, j, k, label, len, len1, len2, ref, ref1, ref2, ref3, ref4;
      ref = this.cases;
      for (i = 0, len = ref.length; i < len; i++) {
        case_tuple = ref[i];
        case_tuple.push(context.newLabel());
      }
      if (this.default_case) {
        default_label = context.newLabel();
      }
      end_label = context.newLabel();
      ref1 = this.cases;
      for (j = 0, len1 = ref1.length; j < len1; j++) {
        ref2 = ref1[j], condition = ref2[0], _ = ref2[1], label = ref2[2];
        condition.codegen(context);
        context.emit(new Instructions.PushVariable('IT'));
        context.emit(new Instructions.Unequal);
        context.emit(new Instructions.JumpIfZero(label));
      }
      if (this.default_case) {
        context.emit(new Instructions.Jump(default_label));
      }
      context.pushBreakLabel(end_label);
      ref3 = this.cases;
      for (k = 0, len2 = ref3.length; k < len2; k++) {
        ref4 = ref3[k], _ = ref4[0], body = ref4[1], label = ref4[2];
        context.emitLabel(label);
        body.codegen(context);
      }
      if (this.default_case) {
        context.emitLabel(default_label);
        this.default_case.codegen(context);
      }
      context.popBreakLabel();
      return context.emitLabel(end_label);
    };

    return Switch;

  })(Statement);

  Loop = (function(superClass) {
    extend(Loop, superClass);

    function Loop(step, condition1, body1) {
      this.step = step;
      this.condition = condition1;
      this.body = body1;
    }

    Loop.prototype.codegen = function(context) {
      var end_label, start_label;
      start_label = context.newLabel();
      end_label = context.newLabel();
      context.emitLabel(start_label);
      if (this.condition) {
        this.condition.codegen(context);
        context.emit(new Instructions.Cast('bool'));
        context.emit(new Instructions.JumpIfZero(end_label));
      }
      this.body.codegen(context);
      if (this.step) {
        this.step.codegen(context);
      }
      context.emit(new Instructions.Jump(start_label));
      return context.emitLabel(end_label);
    };

    return Loop;

  })(Statement);

  Expression = (function(superClass) {
    extend(Expression, superClass);

    function Expression() {
      return Expression.__super__.constructor.apply(this, arguments);
    }

    return Expression;

  })(Node);

  CallExpression = (function(superClass) {
    extend(CallExpression, superClass);

    function CallExpression(func_name, args) {
      this.func_name = func_name;
      this.args = args;
    }

    CallExpression.prototype.codegen = function(context) {
      var arg, i, len, ref;
      ref = this.args;
      for (i = 0, len = ref.length; i < len; i++) {
        arg = ref[i];
        arg.codegen(context);
      }
      return context.emit(new Instructions.Call(this.func_name, this.args.length));
    };

    return CallExpression;

  })(Expression);

  IdentifierExpression = (function(superClass) {
    extend(IdentifierExpression, superClass);

    function IdentifierExpression(identifier) {
      this.identifier = identifier;
    }

    IdentifierExpression.prototype.codegen = function(context) {
      return context.emit(new Instructions.PushVariable(this.identifier));
    };

    return IdentifierExpression;

  })(Expression);

  IndexingExpression = (function(superClass) {
    extend(IndexingExpression, superClass);

    function IndexingExpression(base, index) {
      this.base = base;
      this.index = index;
    }

    IndexingExpression.prototype.codegen = function(context) {
      this.index.codegen(context);
      this.base.codegen(context);
      return context.emit(new Instructions.GetIndex);
    };

    return IndexingExpression;

  })(Expression);

  PropertyAccessExpression = (function(superClass) {
    extend(PropertyAccessExpression, superClass);

    function PropertyAccessExpression(base, property) {
      this.base = base;
      this.property = property;
    }

    PropertyAccessExpression.prototype.codegen = function(context) {
      this.base.codegen(context);
      return context.emit(new Instructions.GetProperty(this.property));
    };

    return PropertyAccessExpression;

  })(Expression);

  CastExpression = (function(superClass) {
    extend(CastExpression, superClass);

    function CastExpression(expression, type) {
      this.expression = expression;
      this.type = type;
    }

    CastExpression.prototype.codegen = function(context) {
      var sane_type;
      this.expression.codegen(context);
      sane_type = (function() {
        switch (this.type) {
          case 'NOOB':
            return 'null';
          case 'TROOF':
            return 'bool';
          case 'NUMBR':
            return 'int';
          case 'NUMBAR':
            return 'float';
          case 'YARN':
            return 'string';
        }
      }).call(this);
      return context.emit(new Instructions.Cast(sane_type, true));
    };

    return CastExpression;

  })(Expression);

  InfinitaryExpression = (function(superClass) {
    extend(InfinitaryExpression, superClass);

    function InfinitaryExpression(operator, operands) {
      this.operator = operator;
      this.operands = operands;
    }

    InfinitaryExpression.prototype.codegen = function(context) {
      var i, len, op, operand, ref;
      this.operands.reverse();
      ref = this.operands;
      for (i = 0, len = ref.length; i < len; i++) {
        operand = ref[i];
        operand.codegen(context);
      }
      op = (function() {
        switch (this.operator) {
          case 'ALL OF':
            return new Instructions.All(this.operands.length);
          case 'ANY OF':
            return new Instructions.Any(this.operands.length);
          case 'SMOOSH':
            return new Instructions.Concat(this.operands.length);
          default:
            throw new CodeGenError('Unknown infinitary operator.');
        }
      }).call(this);
      return context.emit(op);
    };

    return InfinitaryExpression;

  })(Expression);

  BinaryExpression = (function(superClass) {
    extend(BinaryExpression, superClass);

    function BinaryExpression(operator, left, right) {
      this.operator = operator;
      this.left = left;
      this.right = right;
    }

    BinaryExpression.prototype.codegen = function(context) {
      var op;
      this.right.codegen(context);
      this.left.codegen(context);
      op = (function() {
        switch (this.operator) {
          case 'SUM OF':
            return new Instructions.Add;
          case 'DIFF OF':
            return new Instructions.Subtract;
          case 'PRODUKT OF':
            return new Instructions.Multiply;
          case 'QUOSHUNT OF':
            return new Instructions.Divide;
          case 'MOD OF':
            return new Instructions.Modulo;
          case 'BIGGR OF':
            return new Instructions.Max;
          case 'SMALLR OF':
            return new Instructions.Min;
          case 'BOTH OF':
            return new Instructions.And;
          case 'EITHER OF':
            return new Instructions.Or;
          case 'WON OF':
            return new Instructions.Xor;
          case 'BOTH SAEM':
            return new Instructions.Equal;
          case 'DIFFRINT':
            return new Instructions.Unequal;
          default:
            throw new CodeGenError('Unknown binary operator.');
        }
      }).call(this);
      return context.emit(op);
    };

    return BinaryExpression;

  })(Expression);

  UnaryExpression = (function(superClass) {
    extend(UnaryExpression, superClass);

    function UnaryExpression(operator, operand1) {
      this.operator = operator;
      this.operand = operand1;
    }

    UnaryExpression.prototype.codegen = function(context) {
      var op;
      this.operand.codegen(context);
      op = (function() {
        switch (this.operator) {
          case 'NOT':
            return new Instructions.Invert;
          case 'LENGZ OF':
            return new Instructions.GetLength;
          case 'CHARZ OF':
            return new Instructions.FromCharCode;
          case 'ORDZ OF':
            return new Instructions.ToCharCode;
          default:
            throw new CodeGenError('Unknown unary operator.');
        }
      }).call(this);
      return context.emit(op);
    };

    return UnaryExpression;

  })(Expression);

  Literal = (function(superClass) {
    extend(Literal, superClass);

    function Literal() {
      return Literal.__super__.constructor.apply(this, arguments);
    }

    return Literal;

  })(Expression);

  NullLiteral = (function(superClass) {
    extend(NullLiteral, superClass);

    function NullLiteral() {
      return NullLiteral.__super__.constructor.apply(this, arguments);
    }

    NullLiteral.prototype.codegen = function(context) {
      return context.emit(new Instructions.PushLiteral('null', null));
    };

    return NullLiteral;

  })(Literal);

  BoolLiteral = (function(superClass) {
    extend(BoolLiteral, superClass);

    function BoolLiteral(value) {
      this.value = value;
    }

    BoolLiteral.prototype.codegen = function(context) {
      return context.emit(new Instructions.PushLiteral('bool', this.value));
    };

    return BoolLiteral;

  })(Literal);

  IntLiteral = (function(superClass) {
    extend(IntLiteral, superClass);

    function IntLiteral(value) {
      this.value = value;
    }

    IntLiteral.prototype.codegen = function(context) {
      return context.emit(new Instructions.PushLiteral('int', this.value));
    };

    return IntLiteral;

  })(Literal);

  FloatLiteral = (function(superClass) {
    extend(FloatLiteral, superClass);

    function FloatLiteral(value) {
      this.value = value;
    }

    FloatLiteral.prototype.codegen = function(context) {
      return context.emit(new Instructions.PushLiteral('float', this.value));
    };

    return FloatLiteral;

  })(Literal);

  StringLiteral = (function(superClass) {
    extend(StringLiteral, superClass);

    function StringLiteral(value) {
      this.value = value;
    }

    StringLiteral.prototype.codegen = function(context) {
      return context.emit(new Instructions.PushLiteral('string', this.value));
    };

    return StringLiteral;

  })(Literal);

  BukkitLiteral = (function(superClass) {
    extend(BukkitLiteral, superClass);

    function BukkitLiteral() {}

    BukkitLiteral.prototype.codegen = function(context) {
      return context.emit(new Instructions.PushLiteral('object', {}));
    };

    return BukkitLiteral;

  })(Literal);

  this.LOLCoffee.CodeGenError = CodeGenError;

  this.LOLCoffee.CodeGenContext = CodeGenContext;

  this.LOLCoffee.AST = {
    Node: Node,
    Program: Program,
    Statement: Statement,
    FunctionDefinition: FunctionDefinition,
    Declaration: Declaration,
    Return: Return,
    Input: Input,
    Output: Output,
    Assignment: Assignment,
    IndexedAssignment: IndexedAssignment,
    PropertyAssignment: PropertyAssignment,
    Break: Break,
    Loop: Loop,
    Conditional: Conditional,
    Switch: Switch,
    StatementList: StatementList,
    Expression: Expression,
    IdentifierExpression: IdentifierExpression,
    IndexingExpression: IndexingExpression,
    PropertyAccessExpression: PropertyAccessExpression,
    CastExpression: CastExpression,
    CallExpression: CallExpression,
    UnaryExpression: UnaryExpression,
    BinaryExpression: BinaryExpression,
    InfinitaryExpression: InfinitaryExpression,
    Literal: Literal,
    NullLiteral: NullLiteral,
    BoolLiteral: BoolLiteral,
    IntLiteral: IntLiteral,
    FloatLiteral: FloatLiteral,
    StringLiteral: StringLiteral,
    BukkitLiteral: BukkitLiteral
  };

}).call(this);
