// Generated by CoffeeScript 1.12.7

/*
A virtual machine for the LOLCoffee compiler. Defines the instructions that can
be generated by the parse tree nodes and a simple machine interface. The machine
supports loading multiple programs, blocking for asynchronous external calls and
single-step execution.

Example usage:
  codegen_context = ...

  input_callback = ->
    $.get 'input.txt', (text) -> 
      machine.resume text

  output_callback = (output) ->
    $('#result')[0].value += output
    machine.resume()

  halt_callback = ->
    console.log 'Mahine halted. Loading new program...'
     * Generate code for a new program using codegen_context.
    machine.run()

  error_callback = (error) ->
    console.assert error instanceof LOLCoffee.MachineError
    console.log error

  machine = new LOLCoffee.Machine codegen_context,
                                  input_callback,
                                  output_callback,
                                  error_callback,
                                  halt_callback
  machine.run()

Provides:
  LOLCoffee.Machine
  LOLCoffee.MachineError
  LOLCoffee.Instructions

Requires:
  LOLCoffee.DEFAULT_VALUES
 */

(function() {
  var Add, All, And, Any, Assign, AssignAtIndex, BoolOperation, Call, Cast, Concat, DEFAULT_VALUES, DeclareFunction, DeclareVariable, Divide, Equal, Frame, FromCharCode, GetIndex, GetLength, GetProperty, Halt, Input, Invert, Jump, JumpIfZero, Machine, MachineError, MathOperation, Max, Min, Modulo, Multiply, Or, Output, PushLiteral, PushSyscallResult, PushVariable, Return, SetProperty, Subtract, ToCharCode, Unequal, Value, Xor,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  DEFAULT_VALUES = this.LOLCoffee.DEFAULT_VALUES;

  MachineError = (function(superClass) {
    extend(MachineError, superClass);

    function MachineError(message) {
      this.message = message + '.';
    }

    MachineError.prototype.name = 'MachineError';

    return MachineError;

  })(Error);

  Value = (function() {
    function Value(type1, value1) {
      this.type = type1;
      this.value = value1;
    }

    Value.prototype.equal = function(other) {
      var ref, ref1;
      if (((ref = this.type) === 'float' || ref === 'int') && ((ref1 = other.type) === 'float' || ref1 === 'int')) {
        return this.value === other.value;
      } else if (this.type === other.type) {
        return this.value === other.value;
      } else {
        return false;
      }
    };

    Value.prototype.cast = function(to_type, explicit) {
      var result;
      if (explicit == null) {
        explicit = false;
      }
      if (to_type === 'null') {
        throw new MachineError('Cannot cast to NOOB');
      }
      result = null;
      switch (this.type) {
        case 'null':
          if (explicit) {
            if (!(to_type in DEFAULT_VALUES)) {
              throw new MachineError('Unknown type: ' + to_type);
            }
            result = DEFAULT_VALUES[to_type];
          } else {
            if (to_type !== 'bool') {
              throw new MachineError('Cannot implicitly cast NOOB to ' + to_type);
            }
            result = false;
          }
          break;
        case 'bool':
          result = (function() {
            switch (to_type) {
              case 'bool':
                return this.value;
              case 'int':
              case 'float':
                return Number(this.value);
              case 'string':
                if (this.value) {
                  return 'WIN';
                } else {
                  return 'FAIL';
                }
              default:
                throw new MachineError('Unknown type: ' + to_type);
            }
          }).call(this);
          break;
        case 'int':
          result = (function() {
            switch (to_type) {
              case 'bool':
                return this.value !== 0;
              case 'int':
              case 'float':
                return this.value;
              case 'string':
                return String(this.value);
              default:
                throw new MachineError('Unknown type: ' + to_type);
            }
          }).call(this);
          break;
        case 'float':
          result = (function() {
            switch (to_type) {
              case 'bool':
                return this.value !== 0;
              case 'int':
                return Math.floor(this.value);
              case 'float':
                return this.value;
              case 'string':
                return String(this.value);
              default:
                throw new MachineError('Unknown type: ' + to_type);
            }
          }).call(this);
          break;
        case 'string':
          result = (function() {
            switch (to_type) {
              case 'bool':
                return this.value !== '';
              case 'int':
                if (!/^-?\d+$/.test(this.value)) {
                  throw new MachineError("Cannot parse NUMBR from '" + this.value + "'");
                }
                return parseInt(this.value, 10);
              case 'float':
                if (!/^-?(\d+(\.\d*)?|\.\d+)$/.test(this.value)) {
                  throw new MachineError("Cannot parse NUMBAR from '" + this.value + "'");
                }
                return parseFloat(this.value);
              case 'string':
                return this.value;
              default:
                throw new MachineError('Unknown type: ' + to_type);
            }
          }).call(this);
          break;
        default:
          throw new MachineError('Unknown type: ' + this.type);
      }
      return new Value(to_type, result);
    };

    return Value;

  })();

  Frame = (function() {
    function Frame(name, instruction_ptr) {
      this.name = name;
      this.instruction_ptr = instruction_ptr;
      this.variables = {};
      this.stack = [];
    }

    return Frame;

  })();

  Halt = (function() {
    function Halt() {}

    Halt.prototype.exec = function(machine) {
      machine.halted = true;
      return machine.done();
    };

    return Halt;

  })();

  Jump = (function() {
    function Jump(label) {
      this.label = label;
    }

    Jump.prototype.exec = function(machine) {
      return machine.instruction_ptr = machine.labels[this.label];
    };

    return Jump;

  })();

  JumpIfZero = (function() {
    function JumpIfZero(label) {
      this.label = label;
    }

    JumpIfZero.prototype.exec = function(machine) {
      if (machine.getStack().pop().value === false) {
        return machine.instruction_ptr = machine.labels[this.label];
      }
    };

    return JumpIfZero;

  })();

  DeclareFunction = (function() {
    function DeclareFunction(name, label) {
      this.name = name;
      this.label = label;
    }

    DeclareFunction.prototype.exec = function(machine) {
      return machine.functions[this.name] = machine.labels[this.label];
    };

    return DeclareFunction;

  })();

  DeclareVariable = (function() {
    function DeclareVariable(identifier) {
      this.identifier = identifier;
    }

    DeclareVariable.prototype.exec = function(machine) {
      var top_frame;
      if (this.identifier === 'IT') {
        throw new MachineError('Cannot declare the special variable IT');
      }
      top_frame = machine.frames.slice(-1)[0];
      return top_frame.variables[this.identifier] = new Value('null', null);
    };

    return DeclareVariable;

  })();

  Assign = (function() {
    function Assign(identifier) {
      this.identifier = identifier;
    }

    Assign.prototype.exec = function(machine) {
      var global_vars, local_vars, value;
      global_vars = machine.frames[0].variables;
      local_vars = machine.frames.slice(-1)[0].variables;
      value = machine.getStack().pop();
      if (this.identifier in local_vars) {
        return local_vars[this.identifier] = value;
      } else if (this.identifier in global_vars) {
        return global_vars[this.identifier] = value;
      } else if (machine.auto_declare) {
        return local_vars[this.identifier] = value;
      } else {
        throw new MachineError('Assignment to undefined variable: ' + this.identifier);
      }
    };

    return Assign;

  })();

  AssignAtIndex = (function() {
    function AssignAtIndex(identifier) {
      this.identifier = identifier;
    }

    AssignAtIndex.prototype.exec = function(machine) {
      var base, global_vars, index, local_vars, result, scope, value;
      global_vars = machine.frames[0].variables;
      local_vars = machine.frames.slice(-1)[0].variables;
      if (this.identifier in local_vars) {
        scope = local_vars;
      } else if (this.identifier in global_vars) {
        scope = global_vars;
      } else if (machine.auto_declare) {
        scope = local_vars;
      } else {
        throw new MachineError('Assignment to undefined variable: ' + this.identifier);
      }
      base = scope[this.identifier];
      index = machine.getStack().pop();
      value = machine.getStack().pop();
      if (base.type !== 'string') {
        throw new MachineError('Can only index YARNs, not ' + base.type);
      }
      if (index.type !== 'int') {
        throw new MachineError('Can only index using NUMBRs, not ' + index.type);
      }
      if (index.value >= base.value.length) {
        throw new MachineError("Out of bounds: '" + base.value + "'[" + index.value + "]");
      }
      if (value.type !== 'string' || value.value.length !== 1) {
        throw new MachineError('Can only assign single-character YARNs to YARN ' + 'indices, not ' + value.value);
      }
      base = base.value;
      result = base.slice(0, index.value) + value.value + base.slice(index.value + 1);
      return scope[this.identifier] = new Value('string', result);
    };

    return AssignAtIndex;

  })();

  SetProperty = (function() {
    function SetProperty(identifier, property) {
      this.identifier = identifier;
      this.property = property;
    }

    SetProperty.prototype.exec = function(machine) {
      var base, global_vars, local_vars, scope, value;
      global_vars = machine.frames[0].variables;
      local_vars = machine.frames.slice(-1)[0].variables;
      if (this.identifier in local_vars) {
        scope = local_vars;
      } else if (this.identifier in global_vars) {
        scope = global_vars;
      } else if (machine.auto_declare) {
        scope = local_vars;
      } else {
        throw new MachineError('Assignment to undefined variable: ' + this.identifier);
      }
      base = scope[this.identifier];
      value = machine.getStack().pop();
      if (base.type !== 'object') {
        throw new MachineError('Can only access properties on BUKKITs, not ' + base.type);
      }
      base.value[this.property] = value;
      return scope[this.identifier] = base;
    };

    return SetProperty;

  })();

  Input = (function() {
    function Input() {}

    Input.prototype.exec = function(machine) {
      machine.pause();
      return machine.input();
    };

    return Input;

  })();

  Output = (function() {
    function Output() {}

    Output.prototype.exec = function(machine) {
      machine.pause();
      return machine.output(machine.getStack().pop().value);
    };

    return Output;

  })();

  PushSyscallResult = (function() {
    function PushSyscallResult() {}

    PushSyscallResult.prototype.exec = function(machine) {
      var result;
      result = machine.syscall_result;
      result = result ? String(result) : '';
      return machine.getStack().push(new Value('string', result));
    };

    return PushSyscallResult;

  })();

  PushVariable = (function() {
    function PushVariable(identifier) {
      this.identifier = identifier;
    }

    PushVariable.prototype.exec = function(machine) {
      var global_vars, local_vars, value;
      global_vars = machine.frames[0].variables;
      local_vars = machine.frames.slice(-1)[0].variables;
      if (this.identifier in local_vars) {
        value = local_vars[this.identifier];
      } else if (this.identifier in global_vars) {
        value = global_vars[this.identifier];
      } else {
        throw new MachineError('Reference to undefined variable: ' + this.identifier);
      }
      return machine.getStack().push(value);
    };

    return PushVariable;

  })();

  GetIndex = (function() {
    function GetIndex() {}

    GetIndex.prototype.exec = function(machine) {
      var base, index;
      base = machine.getStack().pop();
      index = machine.getStack().pop();
      if (base.type !== 'string') {
        throw new MachineError('Can only index YARNs, not ' + base.type);
      }
      if (index.type !== 'int') {
        throw new MachineError('Can only index using NUMBRs, not ' + index.type);
      }
      if (index.value >= base.value.length) {
        throw new MachineError("Out of bounds: '" + base.value + "'[" + index.value + "]");
      }
      return machine.getStack().push(new Value('string', base.value[index.value]));
    };

    return GetIndex;

  })();

  GetProperty = (function() {
    function GetProperty(property) {
      this.property = property;
    }

    GetProperty.prototype.exec = function(machine) {
      var base;
      base = machine.getStack().pop();
      if (base.type !== 'object') {
        throw new MachineError('Can only access properties on BUKKITs, not ' + base.type);
      }
      if (!(this.property in base.value)) {
        throw new MachineError("Property '" + this.property + "' not found in BUKKIT");
      }
      return machine.getStack().push(base.value[this.property]);
    };

    return GetProperty;

  })();

  PushLiteral = (function() {
    function PushLiteral(type1, value1) {
      this.type = type1;
      this.value = value1;
    }

    PushLiteral.prototype.exec = function(machine) {
      return machine.getStack().push(new Value(this.type, this.value));
    };

    return PushLiteral;

  })();

  Cast = (function() {
    function Cast(type1, explicit1) {
      this.type = type1;
      this.explicit = explicit1 != null ? explicit1 : false;
    }

    Cast.prototype.exec = function(machine) {
      return machine.getStack().push(machine.getStack().pop().cast(this.type, this.explicit));
    };

    return Cast;

  })();

  Call = (function() {
    function Call(func_name, args_count) {
      this.func_name = func_name;
      this.args_count = args_count;
    }

    Call.prototype.exec = function(machine) {
      var _, i, old_stack, ref;
      old_stack = machine.getStack();
      machine.frames.push(new Frame(this.func_name, machine.instruction_ptr));
      for (_ = i = 0, ref = this.args_count; 0 <= ref ? i < ref : i > ref; _ = 0 <= ref ? ++i : --i) {
        machine.getStack().push(old_stack.pop());
      }
      machine.getStack().reverse();
      return machine.instruction_ptr = machine.functions[this.func_name];
    };

    return Call;

  })();

  Return = (function() {
    function Return() {}

    Return.prototype.exec = function(machine) {
      var frame, result;
      result = machine.getStack().pop();
      frame = machine.frames.pop();
      machine.instruction_ptr = frame.instruction_ptr;
      return machine.getStack().push(result);
    };

    return Return;

  })();

  All = (function() {
    function All(args_count) {
      this.args_count = args_count;
    }

    All.prototype.exec = function(machine) {
      var _, arg, args, i, len, result;
      args = (function() {
        var i, ref, results;
        results = [];
        for (_ = i = 0, ref = this.args_count; 0 <= ref ? i < ref : i > ref; _ = 0 <= ref ? ++i : --i) {
          results.push(machine.getStack().pop().cast('bool').value);
        }
        return results;
      }).call(this);
      result = true;
      for (i = 0, len = args.length; i < len; i++) {
        arg = args[i];
        if (!arg) {
          result = false;
          break;
        }
      }
      return machine.getStack().push(new Value('bool', result));
    };

    return All;

  })();

  Any = (function() {
    function Any(args_count) {
      this.args_count = args_count;
    }

    Any.prototype.exec = function(machine) {
      var _, arg, args, i, len, result;
      args = (function() {
        var i, ref, results;
        results = [];
        for (_ = i = 0, ref = this.args_count; 0 <= ref ? i < ref : i > ref; _ = 0 <= ref ? ++i : --i) {
          results.push(machine.getStack().pop().cast('bool').value);
        }
        return results;
      }).call(this);
      result = false;
      for (i = 0, len = args.length; i < len; i++) {
        arg = args[i];
        if (arg) {
          result = true;
          break;
        }
      }
      return machine.getStack().push(new Value('bool', result));
    };

    return Any;

  })();

  Concat = (function() {
    function Concat(args_count) {
      this.args_count = args_count;
    }

    Concat.prototype.exec = function(machine) {
      var _, args;
      args = (function() {
        var i, ref, results;
        results = [];
        for (_ = i = 0, ref = this.args_count; 0 <= ref ? i < ref : i > ref; _ = 0 <= ref ? ++i : --i) {
          results.push(machine.getStack().pop().cast('string').value);
        }
        return results;
      }).call(this);
      return machine.getStack().push(new Value('string', args.join('')));
    };

    return Concat;

  })();

  MathOperation = (function() {
    function MathOperation() {}

    MathOperation.prototype.exec = function(machine, operation) {
      var left, result, right, type;
      left = machine.getStack().pop();
      right = machine.getStack().pop();
      type = 'float' === left.type || 'float' === right.type ? 'float' : 'int';
      left = left.cast(type).value;
      right = right.cast(type).value;
      result = operation(left, right);
      if (type === 'int') {
        result = Math.floor(result);
      }
      return machine.getStack().push(new Value(type, result));
    };

    return MathOperation;

  })();

  Add = (function(superClass) {
    extend(Add, superClass);

    function Add() {
      return Add.__super__.constructor.apply(this, arguments);
    }

    Add.prototype.exec = function(machine) {
      return Add.__super__.exec.call(this, machine, function(x, y) {
        return x + y;
      });
    };

    return Add;

  })(MathOperation);

  Subtract = (function(superClass) {
    extend(Subtract, superClass);

    function Subtract() {
      return Subtract.__super__.constructor.apply(this, arguments);
    }

    Subtract.prototype.exec = function(machine) {
      return Subtract.__super__.exec.call(this, machine, function(x, y) {
        return x - y;
      });
    };

    return Subtract;

  })(MathOperation);

  Multiply = (function(superClass) {
    extend(Multiply, superClass);

    function Multiply() {
      return Multiply.__super__.constructor.apply(this, arguments);
    }

    Multiply.prototype.exec = function(machine) {
      return Multiply.__super__.exec.call(this, machine, function(x, y) {
        return x * y;
      });
    };

    return Multiply;

  })(MathOperation);

  Divide = (function(superClass) {
    extend(Divide, superClass);

    function Divide() {
      return Divide.__super__.constructor.apply(this, arguments);
    }

    Divide.prototype.exec = function(machine) {
      return Divide.__super__.exec.call(this, machine, function(x, y) {
        return x / y;
      });
    };

    return Divide;

  })(MathOperation);

  Modulo = (function(superClass) {
    extend(Modulo, superClass);

    function Modulo() {
      return Modulo.__super__.constructor.apply(this, arguments);
    }

    Modulo.prototype.exec = function(machine) {
      return Modulo.__super__.exec.call(this, machine, function(x, y) {
        return x % y;
      });
    };

    return Modulo;

  })(MathOperation);

  Max = (function(superClass) {
    extend(Max, superClass);

    function Max() {
      return Max.__super__.constructor.apply(this, arguments);
    }

    Max.prototype.exec = function(machine) {
      return Max.__super__.exec.call(this, machine, function(x, y) {
        if (x > y) {
          return x;
        } else {
          return y;
        }
      });
    };

    return Max;

  })(MathOperation);

  Min = (function(superClass) {
    extend(Min, superClass);

    function Min() {
      return Min.__super__.constructor.apply(this, arguments);
    }

    Min.prototype.exec = function(machine) {
      return Min.__super__.exec.call(this, machine, function(x, y) {
        if (x < y) {
          return x;
        } else {
          return y;
        }
      });
    };

    return Min;

  })(MathOperation);

  BoolOperation = (function() {
    function BoolOperation() {}

    BoolOperation.prototype.exec = function(machine, operation) {
      var left, right;
      left = machine.getStack().pop().cast('bool').value;
      right = machine.getStack().pop().cast('bool').value;
      return machine.getStack().push(new Value('bool', operation(left, right)));
    };

    return BoolOperation;

  })();

  And = (function(superClass) {
    extend(And, superClass);

    function And() {
      return And.__super__.constructor.apply(this, arguments);
    }

    And.prototype.exec = function(machine) {
      return And.__super__.exec.call(this, machine, function(x, y) {
        return x && y;
      });
    };

    return And;

  })(BoolOperation);

  Or = (function(superClass) {
    extend(Or, superClass);

    function Or() {
      return Or.__super__.constructor.apply(this, arguments);
    }

    Or.prototype.exec = function(machine) {
      return Or.__super__.exec.call(this, machine, function(x, y) {
        return x || y;
      });
    };

    return Or;

  })(BoolOperation);

  Xor = (function(superClass) {
    extend(Xor, superClass);

    function Xor() {
      return Xor.__super__.constructor.apply(this, arguments);
    }

    Xor.prototype.exec = function(machine) {
      return Xor.__super__.exec.call(this, machine, function(x, y) {
        return x ^ y;
      });
    };

    return Xor;

  })(BoolOperation);

  Equal = (function() {
    function Equal() {}

    Equal.prototype.exec = function(machine) {
      var left, right;
      left = machine.getStack().pop();
      right = machine.getStack().pop();
      return machine.getStack().push(new Value('bool', left.equal(right)));
    };

    return Equal;

  })();

  Unequal = (function() {
    function Unequal() {}

    Unequal.prototype.exec = function(machine) {
      var left, right;
      left = machine.getStack().pop();
      right = machine.getStack().pop();
      return machine.getStack().push(new Value('bool', !left.equal(right)));
    };

    return Unequal;

  })();

  Invert = (function() {
    function Invert() {}

    Invert.prototype.exec = function(machine) {
      var operand;
      operand = machine.getStack().pop().cast('bool').value;
      return machine.getStack().push(new Value('bool', !operand));
    };

    return Invert;

  })();

  GetLength = (function() {
    function GetLength() {}

    GetLength.prototype.exec = function(machine) {
      var operand;
      operand = machine.getStack().pop();
      if (operand.type !== 'string') {
        throw new MachineError('Can only get length of YARNs');
      }
      return machine.getStack().push(new Value('int', operand.value.length));
    };

    return GetLength;

  })();

  FromCharCode = (function() {
    function FromCharCode() {}

    FromCharCode.prototype.exec = function(machine) {
      var operand, str;
      operand = machine.getStack().pop();
      if (operand.type !== 'int') {
        throw new MachineError('Character codes must be NUMBRs, not ' + operand.type);
      }
      str = String.fromCharCode(operand.value);
      return machine.getStack().push(new Value('string', str));
    };

    return FromCharCode;

  })();

  ToCharCode = (function() {
    function ToCharCode() {}

    ToCharCode.prototype.exec = function(machine) {
      var operand;
      operand = machine.getStack().pop();
      if (operand.type !== 'string' || !operand.value.length) {
        throw new MachineError('Can only take character code of non-empty ' + ("YARNs, not '" + operand.type + "'"));
      }
      return machine.getStack().push(new Value('int', operand.value.charCodeAt(0)));
    };

    return ToCharCode;

  })();

  Machine = (function() {
    function Machine(context, input, output, error, done, auto_declare) {
      this.context = context;
      this.input = input;
      this.output = output;
      this.error = error;
      this.done = done;
      this.auto_declare = auto_declare;
      this.instructions = this.context.instructions;
      this.labels = this.context.labels;
      this.reset();
      this.input = this.input || (function(_this) {
        return function() {
          return _this.resume();
        };
      })(this);
      this.output = this.output || (function(_this) {
        return function() {
          return _this.resume();
        };
      })(this);
      this.error = this.error || function() {};
      this.done = this.done || function() {};
      this.auto_declare = this.auto_declare || false;
    }

    Machine.prototype.reset = function() {
      this.instruction_ptr = 0;
      this.frames = [new Frame('{MAIN}', 0)];
      this.frames[0].variables.IT = new Value('null', null);
      this.functions = {};
      this.halted = true;
      this.blocked = false;
      return this.syscall_result = null;
    };

    Machine.prototype.step = function() {
      var e;
      if (this.blocked || this.halted || this.instruction_ptr >= this.instructions.length) {
        throw new MachineError('Cannot execute while blocked, halted or at end');
      }
      try {
        return this.instructions[this.instruction_ptr++].exec(this);
      } catch (error) {
        e = error;
        this.error(e);
        return this.halted = true;
      }
    };

    Machine.prototype.run = function() {
      var results;
      this.halted = false;
      results = [];
      while (!(this.blocked || this.halted)) {
        results.push(this.step());
      }
      return results;
    };

    Machine.prototype.pause = function() {
      return this.blocked = true;
    };

    Machine.prototype.resume = function(syscall_result) {
      if (syscall_result == null) {
        syscall_result = null;
      }
      this.syscall_result = syscall_result;
      this.blocked = false;
      if (!this.halted) {
        return this.run();
      }
    };

    Machine.prototype.getStack = function() {
      return this.frames[this.frames.length - 1].stack;
    };

    return Machine;

  })();

  this.LOLCoffee.Machine = Machine;

  this.LOLCoffee.MachineError = MachineError;

  this.LOLCoffee.Instructions = {
    Halt: Halt,
    PushLiteral: PushLiteral,
    DeclareFunction: DeclareFunction,
    Jump: Jump,
    DeclareVariable: DeclareVariable,
    Assign: Assign,
    AssignAtIndex: AssignAtIndex,
    SetProperty: SetProperty,
    Return: Return,
    Input: Input,
    PushSyscallResult: PushSyscallResult,
    Output: Output,
    PushVariable: PushVariable,
    GetIndex: GetIndex,
    GetProperty: GetProperty,
    Cast: Cast,
    JumpIfZero: JumpIfZero,
    Call: Call,
    All: All,
    Any: Any,
    Concat: Concat,
    Add: Add,
    Subtract: Subtract,
    Multiply: Multiply,
    Divide: Divide,
    Modulo: Modulo,
    Max: Max,
    Min: Min,
    And: And,
    Or: Or,
    Xor: Xor,
    Equal: Equal,
    Unequal: Unequal,
    Invert: Invert,
    GetLength: GetLength,
    FromCharCode: FromCharCode,
    ToCharCode: ToCharCode
  };

}).call(this);
