// Generated by CoffeeScript 1.12.7

/*
A parser for LOLCODE. Takes a list of LOLCODE tokens and produces a parse tree.
Since LOLCODE funciton calls are ambiguous until the function being called is
defined, the Parser keeps track of the arities of all functions defined so far.
This means every time you want to parse a new program that uses previously
defined functions, you will need to provide the last parser's function_arities
to the new one.

In general, you should only need to use parseProgram(). However, similar parse
methods for all other grammar rules are also provided.

Example usage:
  tokenized_program_1 = ...
  tokenized_program_2 = ...
  tokenized_expression = ...
  try
    parser1 = new LOLCoffee.Parser tokenized_program_1
    program_1_ast = parser1.parseProgram()

    parser2 = new LOLCoffee.Parser tokenized_program_2, parser1
    program_2_ast = parser2.parseProgram()

    parser3 = new LOLCoffee.Parser tokenized_expression, parser2
    expression_ast = parser3.parseExpression()
  catch error
    console.assert error instanceof LOLCoffee.ParserError
    console.log error

Provides:
  LOLCoffee.Parser
  LOLCoffee.ParserError

Requires:
  LOLCoffee.AST
  LOLCoffee.DEFAULT_VALUES
  LOLCoffee.UNARY_OPERATORS
  LOLCoffee.BINARY_OPERATORS
  LOLCoffee.INFINITARY_OPERATORS
 */

(function() {
  var AST, BINARY_OPERATORS, DEFAULT_VALUES, INFINITARY_OPERATORS, Parser, ParserError, UNARY_OPERATORS,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty,
    indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  AST = this.LOLCoffee.AST;

  DEFAULT_VALUES = this.LOLCoffee.DEFAULT_VALUES;

  UNARY_OPERATORS = this.LOLCoffee.UNARY_OPERATORS;

  BINARY_OPERATORS = this.LOLCoffee.BINARY_OPERATORS;

  INFINITARY_OPERATORS = this.LOLCoffee.INFINITARY_OPERATORS;

  ParserError = (function(superClass) {
    extend(ParserError, superClass);

    function ParserError(line, message) {
      ParserError.__super__.constructor.call(this, "Line " + line + ": " + message + ".");
    }

    ParserError.prototype.name = 'ParserError';

    return ParserError;

  })(Error);

  Parser = (function() {
    function Parser(tokens, function_arities) {
      this.tokens = tokens;
      this.function_arities = function_arities != null ? function_arities : {};
      this._scope_depth = 0;
      this._in_function = false;
    }

    Parser.prototype.parseProgram = function() {
      var started_with_hai, statements;
      if (!this.tokens.length) {
        return new AST.Program(new AST.StatementList([]));
      }
      started_with_hai = this._nextIs('keyword', 'HAI');
      if (started_with_hai) {
        this._consume();
        if (!this._nextIs('endline')) {
          this._consume('float', '1.2');
        }
        this._consume();
      }
      statements = (function() {
        var results;
        results = [];
        while (this.tokens.length && !this._nextIs('keyword', 'KTHXBYE')) {
          results.push(this.parseStatement());
        }
        return results;
      }).call(this);
      if (this._nextIs('keyword', 'KTHXBYE')) {
        if (!started_with_hai) {
          this._error('KTHXBYE is not allowed when HAI is not used');
        }
        this._consume('keyword', 'KTHXBYE');
        this._consume('endline');
      }
      if (this.tokens.length !== 0) {
        this._error('Unexpected input after program end');
      }
      return new AST.Program(new AST.StatementList(statements));
    };

    Parser.prototype.parseFunctionDefinition = function() {
      var args, body, name, statements;
      this._consume('keyword', 'HOW DUZ I');
      name = this._consume('identifier');
      args = this.parseFunctionArgs();
      this._consume('endline');
      this.function_arities[name] = args.length;
      this._in_function = true;
      statements = (function() {
        var results;
        results = [];
        while (!this._nextIs('keyword', 'IF U SAY SO')) {
          results.push(this.parseStatement());
        }
        return results;
      }).call(this);
      statements.push(new AST.Return(new AST.IdentifierExpression('IT')));
      body = new AST.StatementList(statements);
      this._in_function = false;
      this._consume('keyword', 'IF U SAY SO');
      return new AST.FunctionDefinition(name, args, body);
    };

    Parser.prototype.parseFunctionArgs = function() {
      var args;
      args = [];
      while (this._nextIs('keyword', 'YR')) {
        this._consume();
        args.push(this._consume('identifier'));
        if (this._nextIs('keyword', 'AN')) {
          this._consume();
        } else {
          break;
        }
      }
      return args;
    };

    Parser.prototype.parseStatement = function() {
      var statement;
      if (this._nextIs('keyword', 'IM IN YR')) {
        statement = this.parseLoopStatement();
      } else if (this._nextIs('keyword', 'O RLY?')) {
        statement = this.parseConditionalStatement();
      } else if (this._nextIs('keyword', 'WTF?')) {
        statement = this.parseSwitchStatement();
      } else if (this._nextIs('keyword', 'I HAS A')) {
        statement = this.parseDeclaration();
      } else if (this._nextIs('keyword', 'GIMMEH')) {
        statement = this.parseInputStatement();
      } else if (this._nextIs('keyword', 'VISIBLE')) {
        statement = this.parseOutputStatement();
      } else if (this._nextIs('keyword', 'PUTZ')) {
        statement = this.parseIndexedAssignment();
      } else if (this._nextIs('keyword', 'HOW DUZ I')) {
        if (this._in_function) {
          this._error('Cannot define nested functions');
        }
        statement = this.parseFunctionDefinition();
      } else if (this._nextIs('keyword', 'GTFO')) {
        if (this._scope_depth > 0) {
          statement = new AST.Break;
        } else if (this._in_function) {
          statement = new AST.Return(new AST.NullLiteral);
        } else {
          this._error('GTFO must be inside a loop, switch, or function');
        }
        this._consume();
      } else if (this._nextIs('keyword', 'FOUND YR')) {
        this._consume();
        if (!this._in_function) {
          this._error('FOUND YR must be inside a function');
        }
        statement = new AST.Return(this.parseExpression());
      } else if (this.tokens.length >= 4 && this._nextIs('identifier') && this.tokens[1].is('property') && this.tokens[2].is('identifier') && this.tokens[3].is('keyword', 'R')) {
        statement = this.parsePropertyAssignment();
      } else if (this.tokens.length >= 2 && this._nextIs('identifier') && this.tokens[1].is('keyword', 'R')) {
        statement = this.parseAssignment();
      } else if (this.tokens.length >= 2 && this._nextIs('identifier') && this.tokens[1].is('keyword', 'IS NOW A')) {
        statement = this.parseCastStatement();
      } else {
        statement = new AST.Assignment('IT', this.parseExpression());
      }
      this._consume('endline');
      return statement;
    };

    Parser.prototype.parseInputStatement = function() {
      this._consume('keyword', 'GIMMEH');
      return new AST.Input(this._consume('identifier'));
    };

    Parser.prototype.parseDeclaration = function() {
      var assignment, declaration, type, value, variable;
      this._consume('keyword', 'I HAS A');
      variable = this._consume('identifier');
      declaration = new AST.Declaration(variable);
      if (this._nextIs('keyword', 'ITZ')) {
        this._consume();
        if (this._nextIs('keyword', 'A')) {
          this._consume();
          type = this.parseType();
          value = (function() {
            switch (type) {
              case 'BUKKIT':
                return new AST.BukkitLiteral;
              case 'YARN':
                return new AST.StringLiteral('');
              case 'NUMBR':
                return new AST.IntLiteral(0);
              case 'NUMBAR':
                return new AST.FloatLiteral(0.0);
              case 'TROOF':
                return new AST.BoolLiteral(false);
              case 'NOOB':
                return new AST.NullLiteral;
              default:
                throw new Error("Unknown type: " + type);
            }
          })();
          assignment = new AST.Assignment(variable, value);
        } else {
          assignment = new AST.Assignment(variable, this.parseExpression());
        }
        return new AST.StatementList([declaration, assignment]);
      } else {
        return declaration;
      }
    };

    Parser.prototype.parseAssignment = function() {
      var variable;
      variable = this._consume('identifier');
      this._consume('keyword', 'R');
      return new AST.Assignment(variable, this.parseExpression());
    };

    Parser.prototype.parsePropertyAssignment = function() {
      var identifier, property;
      identifier = this._consume('identifier');
      this._consume('property');
      property = this._consume('identifier');
      this._consume('keyword', 'R');
      return new AST.PropertyAssignment(identifier, property, this.parseExpression());
    };

    Parser.prototype.parseIndexedAssignment = function() {
      var identifier, index, value;
      this._consume('keyword', 'PUTZ');
      value = this.parseExpression();
      this._consume('keyword', 'INTA');
      identifier = this._consume('identifier');
      this._consume('keyword', 'AT');
      index = this.parseExpression();
      return new AST.IndexedAssignment(identifier, index, value);
    };

    Parser.prototype.parseLoopStatement = function() {
      var body, condition, expression, inverted, label, limit, operation, statements, variable, variable_exp;
      this._consume('keyword', 'IM IN YR');
      label = this._consume('identifier');
      operation = variable = condition = null;
      if (!this._nextIs('endline')) {
        if (!(this._nextIs('keyword', 'UPPIN') || this._nextIs('keyword', 'NERFIN') || this._nextIs('identifier'))) {
          this._error('A loop operation must follow the loop label');
        }
        operation = this._consume();
        this._consume('keyword', 'YR');
        variable = this._consume('identifier');
        variable_exp = new AST.IdentifierExpression(variable);
        expression = (function() {
          switch (operation) {
            case 'UPPIN':
              return new AST.BinaryExpression('SUM OF', variable_exp, new AST.IntLiteral(1));
            case 'NERFIN':
              return new AST.BinaryExpression('DIFF OF', variable_exp, new AST.IntLiteral(1));
            default:
              if (this.function_arities[operation] !== 1) {
                this._error('Loop operation must be UPPIN, NERFIN or a unary function');
              }
              return new AST.CallExpression(operation, [variable_exp]);
          }
        }).call(this);
        operation = new AST.Assignment(variable, expression);
        if (!this._nextIs('endline')) {
          if (this._nextIs('keyword', 'WILE')) {
            inverted = false;
          } else if (this._nextIs('keyword', 'TIL')) {
            inverted = true;
          } else {
            this._error('A loop variable must be followed by WILE or TIL');
          }
          this._consume();
          limit = this.parseExpression();
          if (inverted) {
            limit = new AST.UnaryExpression('NOT', limit);
          }
        }
      }
      this._consume('endline');
      this._scope_depth++;
      statements = (function() {
        var results;
        results = [];
        while (!this._nextIs('keyword', 'IM OUTTA YR')) {
          results.push(this.parseStatement());
        }
        return results;
      }).call(this);
      body = new AST.StatementList(statements);
      this._scope_depth--;
      this._consume('keyword', 'IM OUTTA YR');
      if (label !== this._consume('identifier')) {
        this._error('Mismatched loop label');
      }
      return new AST.Loop(operation, limit, body);
    };

    Parser.prototype.parseConditionalStatement = function() {
      var conditional, else_body, else_statements, elseif_body, elseif_statements, elseif_tuples, expression, isNextBlock, ref, then_body, then_statements;
      this._consume('keyword', 'O RLY?');
      this._consume('endline');
      this._consume('keyword', 'YA RLY');
      this._consume('endline');
      isNextBlock = (function(_this) {
        return function() {
          return _this._nextIs('keyword', 'MEBBE') || _this._nextIs('keyword', 'NO WAI') || _this._nextIs('keyword', 'OIC');
        };
      })(this);
      then_statements = (function() {
        var results;
        results = [];
        while (!isNextBlock()) {
          results.push(this.parseStatement());
        }
        return results;
      }).call(this);
      then_body = new AST.StatementList(then_statements);
      elseif_tuples = [];
      while (this._nextIs('keyword', 'MEBBE')) {
        this._consume();
        expression = this.parseExpression();
        this._consume('endline');
        elseif_statements = (function() {
          var results;
          results = [];
          while (!isNextBlock()) {
            results.push(this.parseStatement());
          }
          return results;
        }).call(this);
        elseif_tuples.push([expression, new AST.StatementList(elseif_statements)]);
      }
      else_statements = [];
      else_body = null;
      if (!this._nextIs('keyword', 'OIC')) {
        this._consume('keyword', 'NO WAI');
        this._consume('endline');
        else_statements = (function() {
          var results;
          results = [];
          while (!this._nextIs('keyword', 'OIC')) {
            results.push(this.parseStatement());
          }
          return results;
        }).call(this);
        if (else_statements) {
          else_body = new AST.StatementList(else_statements);
        }
      }
      this._consume('keyword', 'OIC');
      while (elseif_tuples.length) {
        ref = elseif_tuples.pop(), expression = ref[0], elseif_body = ref[1];
        expression = new AST.Assignment('IT', expression);
        conditional = new AST.Conditional(elseif_body, else_body);
        else_body = new AST.StatementList([expression, conditional]);
      }
      return new AST.Conditional(then_body, else_body);
    };

    Parser.prototype.parseSwitchStatement = function() {
      var case_literal_line, cases, default_case, literal, statements;
      this._consume('keyword', 'WTF?');
      this._consume('endline');
      cases = [];
      default_case = null;
      this._scope_depth++;
      while (!this._nextIs('keyword', 'OIC')) {
        if (this._nextIs('keyword', 'OMG')) {
          this._consume();
          case_literal_line = this.tokens[0].line;
          literal = this.parseLiteral();
          if (!(literal instanceof AST.Literal)) {
            this._error('OMG value must be a literal', case_literal_line);
          }
          this._consume('endline');
          statements = (function() {
            var results;
            results = [];
            while (!(this._nextIs('keyword', 'OMG') || this._nextIs('keyword', 'OMGWTF') || this._nextIs('keyword', 'OIC'))) {
              results.push(this.parseStatement());
            }
            return results;
          }).call(this);
          cases.push([literal, new AST.StatementList(statements)]);
        } else if (this._nextIs('keyword', 'OMGWTF')) {
          this._consume();
          this._consume('endline');
          statements = (function() {
            var results;
            results = [];
            while (!this._nextIs('keyword', 'OIC')) {
              results.push(this.parseStatement());
            }
            return results;
          }).call(this);
          default_case = new AST.StatementList(statements);
        } else {
          this._error('Expected OMG, OMGWTF or OIC');
        }
      }
      this._consume();
      this._scope_depth--;
      return new AST.Switch(cases, default_case);
    };

    Parser.prototype.parseExpression = function() {
      var base, keyword, property;
      if (this._nextIs('keyword')) {
        keyword = this.tokens[0].text;
        if (keyword === 'MAEK') {
          return this.parseCastExpression();
        } else if (indexOf.call(UNARY_OPERATORS, keyword) >= 0) {
          return this.parseUnaryExpression();
        } else if (indexOf.call(BINARY_OPERATORS, keyword) >= 0) {
          return this.parseBinaryExpression();
        } else if (indexOf.call(INFINITARY_OPERATORS, keyword) >= 0) {
          return this.parseInfinitaryExpression();
        } else if (keyword === 'WIN' || keyword === 'FAIL' || keyword === 'NOOB') {
          return this.parseLiteral();
        } else {
          return this._error('Invalid keyword at start of expression');
        }
      } else if (this._nextIs('identifier')) {
        base = this.tokens[0].text in this.function_arities ? this.parseFunctionCall() : new AST.IdentifierExpression(this._consume());
        if (this._nextIs('keyword', 'AT')) {
          this._consume();
          return new AST.IndexingExpression(base, this.parseExpression());
        } else if (this._nextIs('property')) {
          this._consume();
          property = this._consume('identifier');
          return new AST.PropertyAccessExpression(base, property);
        } else {
          return base;
        }
      } else {
        return this.parseLiteral();
      }
    };

    Parser.prototype.parseCastExpression = function() {
      var expression;
      this._consume('keyword', 'MAEK');
      expression = this.parseExpression();
      if (this._nextIs('keyword', 'A')) {
        this._consume();
      }
      return new AST.CastExpression(expression, this.parseType());
    };

    Parser.prototype.parseCastStatement = function() {
      var expression, identifier, identifier_expr;
      identifier = this._consume('identifier');
      identifier_expr = new AST.IdentifierExpression(identifier);
      this._consume('keyword', 'IS NOW A');
      expression = new AST.CastExpression(identifier_expr, this.parseType());
      return new AST.Assignment(identifier, expression);
    };

    Parser.prototype.parseType = function() {
      var type;
      type = this._consume('keyword');
      if (!(type in DEFAULT_VALUES)) {
        this._error('Unknown type');
      }
      return type;
    };

    Parser.prototype.parseLiteral = function() {
      var token;
      if (this._nextIs('string')) {
        return this._createStringLiteral(this._consume());
      } else if (this._nextIs('int')) {
        return new AST.IntLiteral(parseInt(this._consume(), 10));
      } else if (this._nextIs('float')) {
        return new AST.FloatLiteral(parseFloat(this._consume()));
      } else if (this._nextIs('keyword')) {
        token = this._consume();
        if (token === 'WIN' || token === 'FAIL') {
          return new AST.BoolLiteral(token === 'WIN');
        } else if (token === 'NOOB') {
          return new AST.NullLiteral;
        } else {
          return this._error('Unexpected keyword while parsing literal', token.line);
        }
      } else {
        return this._error('Could not parse literal');
      }
    };

    Parser.prototype.parseFunctionCall = function() {
      var _, args, func;
      func = this._consume('identifier');
      if (!(func in this.function_arities)) {
        this._error('Undefined function: ' + func);
      }
      args = (function() {
        var i, ref, results;
        results = [];
        for (_ = i = 0, ref = this.function_arities[func]; 0 <= ref ? i < ref : i > ref; _ = 0 <= ref ? ++i : --i) {
          results.push(this.parseExpression());
        }
        return results;
      }).call(this);
      return new AST.CallExpression(func, args);
    };

    Parser.prototype.parseOutputStatement = function() {
      var args;
      this._consume('keyword', 'VISIBLE');
      args = (function() {
        var results;
        results = [];
        while (!(this._nextIs('keyword', '!') || this._nextIs('endline'))) {
          results.push(this.parseExpression());
        }
        return results;
      }).call(this);
      if (this._nextIs('keyword', '!')) {
        this._consume();
      } else {
        args.push(new AST.StringLiteral('\n'));
      }
      return new AST.Output(new AST.InfinitaryExpression('SMOOSH', args));
    };

    Parser.prototype.parseUnaryExpression = function() {
      var operator;
      operator = this._consume('keyword');
      if (indexOf.call(UNARY_OPERATORS, operator) < 0) {
        this._error('Unknown unary operator: ' + operator);
      }
      return new AST.UnaryExpression(operator, this.parseExpression());
    };

    Parser.prototype.parseBinaryExpression = function() {
      var left, operator, right;
      operator = this._consume('keyword');
      if (indexOf.call(BINARY_OPERATORS, operator) < 0) {
        this._error('Unknown binary operator: ' + operator);
      }
      left = this.parseExpression();
      if (this._nextIs('keyword', 'AN')) {
        this._consume();
      }
      right = this.parseExpression();
      return new AST.BinaryExpression(operator, left, right);
    };

    Parser.prototype.parseInfinitaryExpression = function() {
      var args, operator;
      operator = this._consume('keyword');
      if (indexOf.call(INFINITARY_OPERATORS, operator) < 0) {
        this._error('Unknown infinitary operator: ' + operator);
      }
      args = (function() {
        var results;
        results = [];
        while (!(this._nextIs('keyword', 'MKAY') || this._nextIs('endline'))) {
          if (this._nextIs('keyword', 'AN')) {
            this._consume();
          }
          results.push(this.parseExpression());
        }
        return results;
      }).call(this);
      if (this._nextIs('keyword', 'MKAY')) {
        this._consume();
      }
      return new AST.InfinitaryExpression(operator, args);
    };

    Parser.prototype._createStringLiteral = function(str) {
      var buffer, chr, hex, index, parts, variable;
      if (!/^".*"$/.test(str)) {
        this._error('Invalid string literal: ' + str);
      }
      str = str.slice(1, -1);
      parts = [];
      buffer = [];
      index = 0;
      while (index < str.length) {
        chr = str[index];
        if (chr === ':') {
          index++;
          chr = str[index];
          switch (chr) {
            case ')':
              buffer.push('\n');
              break;
            case '>':
              buffer.push('\t');
              break;
            case 'o':
              buffer.push('\g');
              break;
            case '"':
              buffer.push('"');
              break;
            case ':':
              buffer.push(':');
              break;
            case '(':
              hex = str.slice(index).match(/\(([\da-fA-F]+)\)/);
              index += hex[0].length - 1;
              buffer.push(String.fromCharCode(parseInt(hex[1], 16)));
              break;
            case '{':
              variable = str.slice(index).match(/\{([a-zA-Z]\w*)\}/);
              index += variable[0].length - 1;
              if (buffer.length) {
                parts.push(new AST.StringLiteral(buffer.join('')));
              }
              parts.push(new AST.IdentifierExpression(variable[1]));
              buffer = [];
              break;
            case '[':
              this._error('Unicode name embedding not implemented yet: ' + str);
          }
        } else {
          buffer.push(chr);
        }
        index++;
      }
      if (parts.length) {
        if (buffer.length) {
          parts.push(new AST.StringLiteral(buffer.join('')));
        }
        return new AST.InfinitaryExpression('SMOOSH', parts);
      } else {
        return new AST.StringLiteral(buffer.join(''));
      }
    };

    Parser.prototype._consume = function(type, text) {
      var expected, got, line, message;
      if (!((type != null) || (text != null))) {
        return this.tokens.shift().text;
      }
      if (this._nextIs(type, text)) {
        return this._consume();
      } else {
        expected = text != null ? type + "('" + (text || '') + "')" : type;
        if (this.tokens.length === 0) {
          line = '(last)';
          got = '(end of input)';
        } else {
          line = this.tokens[0].line;
          got = this.tokens[0].type + "(" + this.tokens[0].text + ")";
        }
        message = "Expected: " + expected + "; Got: " + got;
        throw new ParserError(line, message);
      }
    };

    Parser.prototype._nextIs = function(type, text) {
      return this.tokens.length && this.tokens[0].is(type, text);
    };

    Parser.prototype._error = function(message, line) {
      if (line) {
        message += ", near " + this.tokens[0].type + ":'" + this.tokens[0].text + "'";
      } else {
        line = this.tokens.length ? this.tokens[0].line : line = '(last)';
      }
      throw new ParserError(line, message);
    };

    return Parser;

  })();

  this.LOLCoffee.Parser = Parser;

  this.LOLCoffee.ParserError = ParserError;

}).call(this);
