// Generated by CoffeeScript 1.12.7

/*
A tokenizer for LOLCODE. Splits a LOLCODE source code string into a list of
tokens. Comments are automatically stripped. Line continuation using ellipses
and soft statement terminators using commas are also taken into account.
Multi-word keywords are captured is separated by any inline whitespace. The
produced tokens are tagged with their physical line numbers for error reporting.

The resulting tokens can be of the following types:
  keyword: "HAI", "YA RLY", ...
  identifier: "X3", "First_Counter", ...
  int literals: 123, -456, 0, ..
  float literals: 1.2, 3., .4, -6.2, ...
  string literals: "a::b:(3F)c:{counter}d:[foo]efg", ...

Example usage:
  tokenizer = new LOLCoffee.Tokenizer source_text
  try
    tokens = tokenizer.tokenize()
  catch error
    console.assert error instanceof LOLCoffee.TokenizerError
    console.log error

Provides:
  LOLCoffee.Tokenizer
  LOLCoffee.TokenizerError

Requires:
  LOLCoffee.KEYWORDS
 */

(function() {
  var COMMENT_REGEX, FLOAT_REGEX, IDENTIFIER_REGEX, INLINE_SPACE_REGEX, INT_REGEX, KEYWORDS, KEYWORD_REGEX, LINE_CONTINUATION_REGEX, MULTILINE_COMMENT_REGEX, PROPERTY_ACCESS_REGEX, STATEMENT_END_REGEX, STRING_REGEX, Token, Tokenizer, TokenizerError, word,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty,
    indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  KEYWORDS = this.LOLCoffee.KEYWORDS;

  INT_REGEX = /^-?\d+/;

  FLOAT_REGEX = /^-?(\d+\.\d*|\.\d+)/;

  IDENTIFIER_REGEX = /^[a-zA-Z]\w*/;

  MULTILINE_COMMENT_REGEX = /^OBTW\b[^]*?\bTLDR\b/;

  COMMENT_REGEX = /^BTW\b.*/;

  LINE_CONTINUATION_REGEX = /^(\u2026|\.\.\.)[ \t\v]*(\r\n|\r|\n)/;

  STATEMENT_END_REGEX = /^(\r\n|\r|\n|,)/;

  INLINE_SPACE_REGEX = /^[ \t\v]+/;

  PROPERTY_ACCESS_REGEX = /^'Z\b/;

  STRING_REGEX = /^"(?::(?:[)>o":]|\([\dA-Fa-f]+\)|\{[A-Za-z]\w*\}|\[[^\[\]]+\])|[^":])*"/;

  KEYWORDS = (function() {
    var i, len, results;
    results = [];
    for (i = 0, len = KEYWORDS.length; i < len; i++) {
      word = KEYWORDS[i];
      results.push(word.replace(/\?/g, '\\?').replace(/\s/g, '[ \\t\\v]+'));
    }
    return results;
  })();

  KEYWORD_REGEX = new RegExp("^(" + (KEYWORDS.join('|')) + ")(?=$|\\b|\\W)");

  TokenizerError = (function(superClass) {
    extend(TokenizerError, superClass);

    function TokenizerError(line, message) {
      TokenizerError.__super__.constructor.call(this, "Line " + line + ": " + message + ".");
    }

    TokenizerError.prototype.name = 'TokenizerError';

    return TokenizerError;

  })(Error);

  Token = (function() {
    function Token(line1, type1, text1) {
      var ref;
      this.line = line1;
      this.type = type1;
      this.text = text1 != null ? text1 : '';
      if (ref = this.type, indexOf.call(Token.prototype.TYPES, ref) < 0) {
        throw new TokenizerError(this.line, 'Invalid token type: ' + this.type);
      }
    }

    Token.prototype.is = function(type, text) {
      return this.type === type && (text === void 0 || this.text === text);
    };

    Token.prototype.TYPES = ['endline', 'keyword', 'identifier', 'int', 'float', 'string', 'property'];

    return Token;

  })();

  Tokenizer = (function() {
    function Tokenizer(text1) {
      this.text = text1;
      this.tokens = [];
      this.line = [];
      this.line_index = 1;
    }

    Tokenizer.prototype.tokenize = function() {
      var line_breaks, match, snippet;
      while (this.text) {
        if (match = this.text.match(INLINE_SPACE_REGEX)) {

        } else if (match = this.text.match(LINE_CONTINUATION_REGEX)) {
          if (STATEMENT_END_REGEX.test(this.text.slice(match[0].length))) {
            this._error('Cannot have an empty line after line continuation');
          }
        } else if (match = this.text.match(STATEMENT_END_REGEX)) {
          this._flushLine();
        } else if (match = this.text.match(COMMENT_REGEX)) {

        } else if (match = this.text.match(MULTILINE_COMMENT_REGEX)) {
          if (this.line.length) {
            this._error('Multiline comments must start on a new line');
          }
        } else if (match = this.text.match(KEYWORD_REGEX)) {
          this._emit('keyword', match[0].replace(/\s+/g, ' '));
        } else if (match = this.text.match(PROPERTY_ACCESS_REGEX)) {
          this._emit('property', match[0]);
        } else if (match = this.text.match(IDENTIFIER_REGEX)) {
          this._emit('identifier', match[0]);
        } else if (match = this.text.match(FLOAT_REGEX)) {
          this._emit('float', match[0]);
        } else if (match = this.text.match(INT_REGEX)) {
          this._emit('int', match[0]);
        } else if (match = this.text.match(STRING_REGEX)) {
          this._emit('string', match[0]);
        } else {
          snippet = this.text.match(/^.*/)[0];
          this._error('Unrecognized sequence at: ' + snippet);
        }
        line_breaks = match[0].match(/\r\n|\r|\n/g);
        if (line_breaks) {
          this.line_index += line_breaks.length;
        }
        this.text = this.text.slice(match[0].length);
      }
      this._flushLine();
      return this.tokens;
    };

    Tokenizer.prototype._flushLine = function() {
      if (this.line.length) {
        this.tokens = this.tokens.concat(this.line);
        this.tokens.push(new Token(this.line_index, 'endline'));
      }
      return this.line = [];
    };

    Tokenizer.prototype._emit = function(type, value) {
      return this.line.push(new Token(this.line_index, type, value));
    };

    Tokenizer.prototype._error = function(message) {
      throw new TokenizerError(this.line_index, message);
    };

    return Tokenizer;

  })();

  this.LOLCoffee.Tokenizer = Tokenizer;

  this.LOLCoffee.TokenizerError = TokenizerError;

}).call(this);
